### ISSUE TITLE
I ma andy's fans

### ISSUE THREAD

**Issue by ghost** [nelsonGX/small-python-terminal-game#1]
# @andy, when could u send me ur most beautiful classmate's photo? I am sincerely expecting for that!

( By the way, ANDY IS MOST SKILLFUL CODE ENGENIEER IN TAIWAN !!!!!!!!!!

**Comment by gucooing** [comment]
send me photo！@letheriver2007

**Comment by ghost** [comment]
> send me photo！@letheriver2007

OH NO PLS GO AWAY
GAY MAN! 呕

**Comment by nelsonGX** [comment]
what the fuk bro 💀should make this repo private

**Comment by ghost** [comment]
> what the fuk bro 💀should make this repo private

oh no, i am andys biggest fans, pls

**Comment by WatchAndyTW** [comment]
I told you bro

**Comment by letheriver2007** [comment]
> I told you bro

noway, i even sont know her id
